<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>{$title}</title>
<meta name="author" content="Tomas Goldir - tomas.goldir@gmail.com" />
<link rel="stylesheet" type="text/css" href="{$baseUri}css/screen.css" />
<script src="http://www.google.com/jsapi"></script>
<script>google.load("jquery", "1.3.2")</script>
<script src="js/jquery.corners.min.js"></script>
<script><!--
$(document).ready(function() {
	$(".container").corners('10px');
});
--></script>
<script type="text/javascript" src="js/jquery.nette.js"></script>
</head>

<body>
<div class="container">
	{ifCurrent Default:default}{else}
	<div class="navigation">
		<a href="{link Default:default}">Back to mainpage</a>
	</div>
	{/if}

	<h1>{$title}</h1>

	<div class="content">
	{snippet}
	<?php /* $content->render(); // nette-0.8 */ ?>
	{include $content}
	{/snippet}
	</div>
</div>
</body>

</html>
