<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>{$title}</title>
<link rel="stylesheet" type="text/css" href="{$baseUri}css/default.css" />
<meta name="author" content="Tomas Goldir - tomas.goldir@gmail.com" />
</head>

<body>
<?php /* $content->render(); // nette-0.8 */ ?>
{include $content}
</body>

</html>
