<h1>{!_"WebCreatio is back"}!</h1>
<p>Now targeted on a11y, c11y and m12n, with 1337 d11n and support for i18n ;-P Huh? Do you know these <a href="http://en.wikipedia.org/wiki/Numeronym">numeronyms</a>, right? ;o)</p>

<div class="topmenu">
	<ul>
		<li><a href="phpdoc/">phpdoc/</a></li>
		<li><a href="{link CKEditor:}">CKEditor</a></li>
		<li><a href="GettextExtractor/ge.php">GettextExtractor</a></li>
	</ul>
</div>

<div class="software_used"><h2>Využívaný software</h2>
	<ul>
		<li>OS: Linux, Windows, ?MacOSX?, bsd, solaris, ???</li>
		<li><a href="http://httpd.apache.org">Apache</a> 2.2</li>
		<li><a href="http://php.net">PHP</a> 5.2</li>
		<li><a href="http://git-scm.com">git</a> 1.6</li>
		<li><a href="http://nettephp.com">Nette</a> 0.9 (<a href="http://charlie.cz/gettext-extractor/">GettextExtractor</a> revize 2)</li>
		<li><a href="http://dibiphp.com">dibi</a> 1.1</li>
	</ul>
</div>
