<div class="topmenu">
	<h2>{!_"Actions"}:</h2>
	<ul>
		<li>{!_"User"}: <a href="{link User:login}">{!_"Login"}</a>
			| <a href="{link User:logout}">{!_"Logout"}</a>
			| <a href="{link User:profile}">{!_"Profile"}</a>
			| <a href="{link User:register}">{!_"Register"}</a>
			| <a href="{link User:activation}">{!_"Activation"}</a>
			| <a href="{link User:forgottenPassword}">{!_"Forgotten password"}</a></li>

		<li>{!_"Browsers"}: <a href="{link Database:}">{!_"Database"}</a>
			| CKFinder</li>

		<li>{!_"Editors"}: CKEditor | Texy!</li>

		<li>{!_"Widgets"}: <a href="{link Mp3Player:}">{!_"MP3 Player"}</a>
			| <a href="{link PartyPhoto:}">PartyPhoto</a>

		<li>{!_"Examples"}: <a href="{link AutoComplete:}">AutoComplete</a>
			| <a href="{link loremIpsum}">Lorem Ipsum</a>
			| <a href="{link Css:}">Colorpicker</a>
			| <a href="{link Moneyzzz:}">Moneyzzz</a></li>

		<li>{!_"Links"}: <a href="phpdoc/">{!_"Documentation"}</a>
			| <a href="GettextExtractor/ge.php">GettextExtractor</a></li>
	</ul>
</div>

<div class="requirements">
	<h2>{!_"Requirements"}:</h2>
	<ul>
		<li>{!_"Operating system"}: Linux, Windows or Mac OSX</li>
		<li><a href="http://httpd.apache.org">Apache</a> 2.2</li>
		<li><a href="http://php.net">PHP</a> 5.2</li>
		<li><a href="http://git-scm.com">git</a> 1.6</li>
		<li><a href="http://nettephp.com">Nette</a> 0.9.1 (<a href="http://charlie.cz/gettext-extractor/">GettextExtractor</a> revision 2)</li>
		<li><a href="http://dibiphp.com">dibi</a> 1.1</li>
	</ul>
</div>

<div class="footer">Nette {!_"Version"|lower}: <?php echo FRAMEWORK::VERSION; ?></div>
